export const APEX_LEGENDS_API_BASE_URL = import.meta.env.VITE_APEX_LEGENDS_API;
export const APEX_LEGENDS_API_AUTH_TOKEN = import.meta.env
  .VITE_APEX_LEGENDS_API_SECRET_TOKEN;
export const APEX_LEGENDS_API_MAP_ROTATION_ENDPOINT = import.meta.env
  .VITE_APEX_LEGENDS_API_MAP_ROTATION_ENDPOINT;
